#!/usr/bin/env python3
"""generate-nodes.py — BCM node provisioning from a CSV inventory.

Reads a node inventory CSV (exported from a spreadsheet) and generates
the cmsh commands to add every node: device creation, provisioning
interface, DHCP, MAC, category, and BMC interfaces for GPU nodes.

CSV columns, in this order (header row required):
    hostname,ip,mac,role,category,interface,bmc_ip

  hostname   short hostname, e.g. k8s-ctrl-1, gpu-worker-001
  ip         provisioning-network IP, e.g. 10.10.15.50
  mac        provisioning NIC MAC, e.g. 00:50:56:b3:aa:bb
  role       ctrl | worker | gpu   (informational; drives grouping)
  category   BCM category, e.g. runai-cp-cat, runai-dgx-cat
  interface  provisioning interface name, e.g. ens33, enp225s0f0np0
  bmc_ip     BMC IP on the OOB network (empty for non-GPU nodes)

Usage:
    # 1. Make a skeleton CSV to fill in (MACs/IPs are placeholders):
    ./generate-nodes.py --skeleton --ctrl 3 --workers 4 --gpus 74 > inventory.csv

    # 2. Fill in real MACs/IPs/hostnames in your spreadsheet, export CSV.

    # 3. Validate only:
    ./generate-nodes.py --check inventory.csv

    # 4. Generate the cmsh script (review it before running):
    ./generate-nodes.py inventory.csv > provision-nodes.sh
    bash -n provision-nodes.sh   # syntax check
    # then run it on the BCM head node

Validation performed: required fields present, no duplicate hostname /
IP / MAC, IP parses as IPv4, MAC looks like a MAC, BMC IP present for
gpu role.
"""

import argparse
import csv
import ipaddress
import re
import sys

COLUMNS = ["hostname", "ip", "mac", "role", "category", "interface", "bmc_ip"]
MAC_RE = re.compile(r"^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$")
ROLES = {"ctrl", "worker", "gpu"}


def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def load(path):
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != COLUMNS:
            fail(f"expected header exactly: {','.join(COLUMNS)}\n"
                 f"got: {','.join(reader.fieldnames or [])}")
        rows = [dict(r) for r in reader if any((r or {}).values())]
    return rows


def check(rows):
    errors = []
    seen_host, seen_ip, seen_mac = set(), set(), set()
    for i, r in enumerate(rows, start=2):  # 1-based + header
        tag = f"line {i} ({r.get('hostname', '?')})"
        for c in COLUMNS:
            if c != "bmc_ip" and not (r.get(c) or "").strip():
                errors.append(f"{tag}: missing required field '{c}'")
        host = (r.get("hostname") or "").strip()
        ip = (r.get("ip") or "").strip()
        mac = (r.get("mac") or "").strip().lower()
        role = (r.get("role") or "").strip()
        if host in seen_host:
            errors.append(f"{tag}: duplicate hostname '{host}'")
        seen_host.add(host)
        if ip in seen_ip:
            errors.append(f"{tag}: duplicate IP '{ip}'")
        seen_ip.add(ip)
        try:
            ipaddress.IPv4Address(ip)
        except ValueError:
            errors.append(f"{tag}: invalid IPv4 '{ip}'")
        if mac in seen_mac:
            errors.append(f"{tag}: duplicate MAC '{mac}'")
        seen_mac.add(mac)
        if not MAC_RE.match(mac):
            errors.append(f"{tag}: malformed MAC '{mac}' (want 00:11:22:33:44:55)")
        if role not in ROLES:
            errors.append(f"{tag}: role must be one of {sorted(ROLES)}, got '{role}'")
        if role == "gpu" and not (r.get("bmc_ip") or "").strip():
            errors.append(f"{tag}: gpu role requires bmc_ip")
        bmc = (r.get("bmc_ip") or "").strip()
        if bmc:
            try:
                ipaddress.IPv4Address(bmc)
            except ValueError:
                errors.append(f"{tag}: invalid BMC IPv4 '{bmc}'")
    return errors


def generate(rows):
    out = []
    out.append("#!/bin/bash")
    out.append("# Generated by generate-nodes.py — REVIEW BEFORE RUNNING on the BCM head node.")
    out.append(f"# Nodes: {len(rows)}")
    out.append("set -euo pipefail")
    out.append("")
    for r in rows:
        h, ip = r["hostname"].strip(), r["ip"].strip()
        mac = r["mac"].strip().lower()
        cat, iface = r["category"].strip(), r["interface"].strip()
        bmc = (r.get("bmc_ip") or "").strip()
        out.append(f'echo "==> {h} ({ip})"')
        # combined one-liner: add + provisioning interface + category
        out.append(f'cmsh -c "device ; add physicalnode {h} {ip} {iface} ; '
                   f'set provisioninginterface {iface} ; set category {cat} ; commit"')
        out.append(f'cmsh -c "device ; use {h} ; interfaces ; use {iface} ; '
                   f'set dhcp yes ; commit"')
        out.append(f'cmsh -c "device ; use {h} ; set mac {mac} ; commit"')
        if bmc:
            out.append(f'cmsh -c "device ; use {h} ; interfaces ; '
                       f'add bmc ipmi0 {bmc} mgmtnet ; commit"')
        out.append("")
    out.append('echo "All nodes provisioned. Verify: cmsh -c \'device list\'"')
    return "\n".join(out)


def skeleton(ctrl, workers, gpus):
    """Emit a fill-in CSV. IPs/MACs are placeholders — replace with real values."""
    w = csv.writer(sys.stdout)
    w.writerow(COLUMNS)
    ip = ipaddress.IPv4Address("10.10.15.50")
    mac_n = 0

    def mac():
        nonlocal mac_n
        mac_n += 1
        return "00:50:56:b3:%02x:%02x" % ((mac_n >> 8) & 0xFF, mac_n & 0xFF)

    def nxt():
        nonlocal ip
        cur = str(ip)
        ip += 1
        return cur

    for i in range(1, ctrl + 1):
        w.writerow([f"k8s-ctrl-{i}", nxt(), mac(), "ctrl", "runai-cp-cat", "ens33", ""])
    for i in range(1, workers + 1):
        w.writerow([f"k8s-worker-{i}", nxt(), mac(), "worker", "runai-wrk-cat", "ens33", ""])
    for i in range(1, gpus + 1):
        # BMC IPs on the OOB network — adjust the base to the site plan
        w.writerow([f"gpu-worker-{i:03d}", nxt(), mac(), "gpu",
                    "runai-dgx-cat", "enp225s0f0np0", f"10.10.16.{100 + i}"])
    print(f"# skeleton: {ctrl} ctrl + {workers} workers + {gpus} gpus — "
          f"REPLACE all placeholder MACs/IPs", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description="Generate BCM cmsh node-provisioning from CSV.")
    ap.add_argument("csv", nargs="?", help="inventory CSV file")
    ap.add_argument("--check", action="store_true", help="validate only")
    ap.add_argument("--skeleton", action="store_true", help="emit fill-in CSV")
    ap.add_argument("--ctrl", type=int, default=3)
    ap.add_argument("--workers", type=int, default=0)
    ap.add_argument("--gpus", type=int, default=0)
    a = ap.parse_args()

    if a.skeleton:
        skeleton(a.ctrl, a.workers, a.gpus)
        return
    if not a.csv:
        ap.error("provide a CSV file (or --skeleton)")
    rows = load(a.csv)
    errors = check(rows)
    if errors:
        print(f"{len(errors)} problem(s) in {a.csv}:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)
    print(f"OK: {len(rows)} nodes validated ({a.csv})", file=sys.stderr)
    if not a.check:
        print(generate(rows))


if __name__ == "__main__":
    main()
