#!/usr/bin/env python3
"""generate-users.py — BCM user accounts from a CSV inventory.

Lesson learned the hard way: keep the cmsh user commands MINIMAL.
Passing id, groupid, homedirectory, loginshell etc. causes weird
interactions with BCM's OpenLDAP backend (shell/ID/home weirdness).
Just add the user and set a temp password — let BCM assign the
defaults.

CSV columns, in this order (header row required):
    username,sudo

  username  login name, e.g. bcm-admin
  sudo      yes | no — whether the user gets the sudoers drop-in
            (section 15.2), not via cmsh

Usage:
    cp accounts-template.csv accounts.csv   # fill in real usernames
    ./generate-users.py accounts.csv > create-users.sh
    ./generate-users.py --sudoers accounts.csv > bcm-admins   # sudoers drop-in
    bash -n create-users.sh
    # fill in <TEMP> passwords, review, then run on the BCM head node as root
"""

import argparse
import csv
import re
import sys

COLUMNS = ["username", "sudo"]
USER_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")


def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def load(path):
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != COLUMNS:
            fail(f"expected header exactly: {','.join(COLUMNS)}\n"
                 f"got: {','.join(reader.fieldnames or [])}")
        rows = [r for r in reader if any((r or {}).values())]
    return rows


def check(rows):
    errors, seen = [], set()
    for i, r in enumerate(rows, start=2):
        u = (r["username"] or "").strip()
        tag = f"line {i} ({u or '?'})"
        if not USER_RE.match(u):
            errors.append(f"{tag}: bad username '{u}'")
        if u in seen:
            errors.append(f"{tag}: duplicate username '{u}'")
        seen.add(u)
        if (r["sudo"] or "").strip().lower() not in ("yes", "no"):
            errors.append(f"{tag}: sudo must be yes|no")
    return errors


def main():
    ap = argparse.ArgumentParser(description="Generate BCM user-creation commands from CSV.")
    ap.add_argument("csv", help="account inventory CSV")
    ap.add_argument("--check", action="store_true", help="validate only")
    ap.add_argument("--sudoers", action="store_true",
                    help="emit the /etc/sudoers.d/bcm-admins drop-in instead")
    a = ap.parse_args()

    rows = load(a.csv)
    errors = check(rows)
    if errors:
        print(f"{len(errors)} problem(s):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)
    print(f"OK: {len(rows)} users validated", file=sys.stderr)
    if a.check:
        return

    if a.sudoers:
        admins = [r["username"].strip() for r in rows
                  if r["sudo"].strip().lower() == "yes"]
        print("# BCM-managed administrative users — least privilege: list only admins")
        for u in admins:
            print(f"{u} ALL=(ALL:ALL) ALL")
        return

    print("#!/bin/bash")
    print("# Generated by generate-users.py — fill in <TEMP> passwords, REVIEW, then run as root on the BCM head node.")
    print("# Minimal switches on purpose: BCM/OpenLDAP assigns id, home, and shell defaults.")
    print("# cmsh -q stops at the first error.")
    print("set -uo pipefail")
    print()
    for r in rows:
        u = r["username"].strip()
        print(f'cmsh -q -c "user; add {u}; set password <TEMP-{u.upper()}>; commit"')
    print()
    print('cmsh -c "user; list"')


if __name__ == "__main__":
    main()
